version: '3.1'

services:
  db:
    image: postgres:11.6
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_fcd
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always

  collector:
    build: .
    command: coldev
    volumes:
      - ./dev_dbconfig.js:/app/ormconfig.js
    restart: always

  tracker:
    build: .
    command: tracking
    volumes:
      - ./dev_dbconfig.js:/app/ormconfig.js
    restart: always

  server:
    build: .
    command: dev
    ports:
      - "3050:3050"
    volumes:
      - ./dev_dbconfig.js:/app/ormconfig.js
    restart: always
